version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_DB: $TYPEORM_DATABASE
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nodeapp:
    container_name: nodeapp
    image: nodeapp:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      POSTGRES_HOST: $TYPEORM_HOST
      POSTGRES_PORT: $TYPEORM_PORT
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_DB: $TYPEORM_DATABASE
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./src:/app/src

networks:
  backend:
    driver: bridge

volumes:
  pgdata: