FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

CMD ["exit", "0"]

FROM node:20-alpine as prod

COPY package*.json ./

RUN npm ci --only=production \
    && npm cache clean --force

COPY /dist .
COPY /doc ./doc

ENV NODE_ENV production

CMD ["node", "main"]