version: '3.8'

services:
  postgres:
    container_name: mypostgres
    image: mypostgresimage:latest
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  nodeapp:
    container_name: mynodeapp
    image: mynodeappimage:latest
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "$PORT:$PORT"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
